package com.turismo.service_microservice.entity;

public enum TipoActividad {
    TREKKING,
    OBSERVACION_FAUNA,
    SENDERISMO,
    KAYAK,
    CANOA,
    SNORKEL,
    BUCEO,
    OBSERVACION_AVES,
    PASEOS_CABALLO,
    CICLISMO,
    VISITAS_GUIADAS,
    VOLUNTARIADO_REFORESTACION,
    LIMPIEZA_PLAYAS,
    CONSERVACION_FAUNA,
    CAMPAMENTOS_EDUCATIVOS,
    TALLERES_MEDIOAMBIENTALES,
    FOTOGRAFIA_NATURALEZA,
    CARRERAS_ORIENTACION,
    ESCALADA,
    VIA_FERRATA,
    PESCA_SOSTENIBLE,
    AGRICULTURA_ECOLOGICA,
    VISITAS_COMUNIDADES_INDIGENAS,
    TERAPIAS_NATURALEZA
}
